import { createContext, useContext, useState } from "react";
import type { ReactNode } from "react";

type Language = "en" | "es" | "fr" | "de" | "zh";

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    welcomeTitle: "Welcome to Assemble",
    welcomeSubtitle: "Choose your role to get started",
    contractorTitle: "I'm a Contractor",
    contractorDesc: "Manage clients, permits, tasks, and project schedules",
    contractorButton: "Access Admin Dashboard",
    homeownerTitle: "I'm a Homeowner",
    homeownerDesc: "View your project status, documents, and communicate with your contractor",
    homeownerButton: "View My Projects",
    myProjects: "My Projects",
    projectStatus: "Project Status",
    inProgress: "In Progress",
    projectProgress: "Project Progress",
    excellentProgress: "Excellent progress! Your project is nearly complete.",
    greatProgress: "Great progress! Your project is on track for completion.",
    goodStart: "Good start! Your project is progressing well.",
    justBegun: "Your project has just begun.",
    timeline: "Timeline",
    weeks: "Weeks",
    documents: "Documents",
    photos: "Photos",
    messages: "Messages",
    new: "New",
    recentUpdates: "Recent Updates",
    upcomingMilestones: "Upcoming Milestones",
    contactContractor: "Contact Your Contractor",
    contactDesc: "Have questions? Send a message to your contractor team.",
    sendMessage: "Send Message",
    loadingProgress: "Loading progress...",
    propertyValue: "Property Value",
    currentValue: "Current Property Value",
    postRenovationValue: "Post-Renovation Value",
    estimatedIncrease: "Estimated Value Increase",
    roi: "ROI",
    aiRenovationVisualizer: "AI Renovation Visualizer",
    // Landing page
    heroTitle: "The Complete Platform for Construction Projects",
    heroSubtitle: "Whether you're a contractor managing multiple clients or a homeowner tracking your renovation, Assemble connects everyone and keeps projects on track.",
    getStartedFree: "Get Started Free",
    watchDemo: "Watch Demo",
    forContractors: "For Contractors",
    contractorSubtitle: "Powerful tools to streamline your contracting business and manage multiple projects with ease.",
    forHomeowners: "For Homeowners",
    homeownerSubtitle: "Stay connected and informed throughout your renovation journey with real-time updates and direct communication.",
    clientManagement: "Client Management",
    clientManagementDesc: "Keep track of all your clients and their project details in one centralized location.",
    projectScheduling: "Project Scheduling",
    projectSchedulingDesc: "Plan and visualize your project timelines with an integrated calendar system.",
    permitTracking: "Permit Tracking",
    permitTrackingDesc: "Monitor permit applications and approvals to keep projects compliant and on schedule.",
    taskManagement: "Task Management",
    taskManagementDesc: "Assign, track, and manage tasks across your team with priority levels and due dates.",
    propertyValueTracking: "Property Value Tracking",
    propertyValueTrackingDesc: "Monitor your property's estimated value increase as your renovation progresses.",
    realTimeUpdates: "Real-Time Progress Updates",
    realTimeUpdatesDesc: "Stay informed with live project updates and milestone tracking throughout your renovation.",
    photoDocumentation: "Photo Documentation",
    photoDocumentationDesc: "Access all project photos and visual progress updates in one organized gallery.",
    directCommunication: "Direct Communication",
    directCommunicationDesc: "Message contractors directly and get quick responses to all your questions.",
    pricing: "Simple, Transparent Pricing",
    pricingSubtitle: "Choose the plan that fits your needs. All plans include a 14-day free trial.",
    mostPopular: "Most Popular",
    perMonth: "/month",
    startFreeTrial: "Start Free Trial",
    readyToStart: "Ready to Get Started?",
    readySubtitle: "Join thousands of contractors and homeowners managing their projects more efficiently",
    getStartedToday: "Get Started Today",
    getStarted: "Get Started",
  },
  es: {
    welcomeTitle: "Bienvenido a Assemble",
    welcomeSubtitle: "Elige tu rol para comenzar",
    contractorTitle: "Soy Contratista",
    contractorDesc: "Gestionar clientes, permisos, tareas y cronogramas de proyectos",
    contractorButton: "Acceder al Panel de Administración",
    homeownerTitle: "Soy Propietario",
    homeownerDesc: "Ver el estado de tu proyecto, documentos y comunicarte con tu contratista",
    homeownerButton: "Ver Mis Proyectos",
    myProjects: "Mis Proyectos",
    projectStatus: "Estado del Proyecto",
    inProgress: "En Progreso",
    projectProgress: "Progreso del Proyecto",
    excellentProgress: "¡Excelente progreso! Tu proyecto está casi completo.",
    greatProgress: "¡Gran progreso! Tu proyecto va por buen camino.",
    goodStart: "¡Buen comienzo! Tu proyecto está progresando bien.",
    justBegun: "Tu proyecto acaba de comenzar.",
    timeline: "Cronograma",
    weeks: "Semanas",
    documents: "Documentos",
    photos: "Fotos",
    messages: "Mensajes",
    new: "Nuevo",
    recentUpdates: "Actualizaciones Recientes",
    upcomingMilestones: "Próximos Hitos",
    contactContractor: "Contacta a tu Contratista",
    contactDesc: "¿Tienes preguntas? Envía un mensaje a tu equipo de contratistas.",
    sendMessage: "Enviar Mensaje",
    loadingProgress: "Cargando progreso...",
    propertyValue: "Valor de la Propiedad",
    currentValue: "Valor Actual de la Propiedad",
    postRenovationValue: "Valor Post-Renovación",
    estimatedIncrease: "Aumento Estimado de Valor",
    roi: "ROI",
    aiRenovationVisualizer: "Visualizador de Renovación IA",
    // Landing page
    heroTitle: "La Plataforma Completa para Proyectos de Construcción",
    heroSubtitle: "Ya seas un contratista gestionando múltiples clientes o un propietario rastreando tu renovación, Assemble conecta a todos y mantiene los proyectos en marcha.",
    getStartedFree: "Comenzar Gratis",
    watchDemo: "Ver Demo",
    forContractors: "Para Contratistas",
    contractorSubtitle: "Herramientas poderosas para optimizar tu negocio de contratación y gestionar múltiples proyectos con facilidad.",
    forHomeowners: "Para Propietarios",
    homeownerSubtitle: "Mantente conectado e informado durante tu viaje de renovación con actualizaciones en tiempo real y comunicación directa.",
    clientManagement: "Gestión de Clientes",
    clientManagementDesc: "Mantén un registro de todos tus clientes y los detalles de sus proyectos en una ubicación centralizada.",
    projectScheduling: "Programación de Proyectos",
    projectSchedulingDesc: "Planifica y visualiza los plazos de tus proyectos con un sistema de calendario integrado.",
    permitTracking: "Seguimiento de Permisos",
    permitTrackingDesc: "Monitorea las solicitudes y aprobaciones de permisos para mantener los proyectos conformes y a tiempo.",
    taskManagement: "Gestión de Tareas",
    taskManagementDesc: "Asigna, rastrea y gestiona tareas en tu equipo con niveles de prioridad y fechas de vencimiento.",
    propertyValueTracking: "Seguimiento del Valor de la Propiedad",
    propertyValueTrackingDesc: "Monitorea el aumento estimado del valor de tu propiedad a medida que avanza tu renovación.",
    realTimeUpdates: "Actualizaciones de Progreso en Tiempo Real",
    realTimeUpdatesDesc: "Mantente informado con actualizaciones de proyecto en vivo y seguimiento de hitos durante tu renovación.",
    photoDocumentation: "Documentación Fotográfica",
    photoDocumentationDesc: "Accede a todas las fotos del proyecto y actualizaciones visuales de progreso en una galería organizada.",
    directCommunication: "Comunicación Directa",
    directCommunicationDesc: "Envía mensajes a los contratistas directamente y obtén respuestas rápidas a todas tus preguntas.",
    pricing: "Precios Simples y Transparentes",
    pricingSubtitle: "Elige el plan que se adapte a tus necesidades. Todos los planes incluyen una prueba gratuita de 14 días.",
    mostPopular: "Más Popular",
    perMonth: "/mes",
    startFreeTrial: "Iniciar Prueba Gratuita",
    readyToStart: "¿Listo para Comenzar?",
    readySubtitle: "Únete a miles de contratistas y propietarios que gestionan sus proyectos de manera más eficiente",
    getStartedToday: "Comenzar Hoy",
    getStarted: "Comenzar",
  },
  fr: {
    welcomeTitle: "Bienvenue sur Assemble",
    welcomeSubtitle: "Choisissez votre rôle pour commencer",
    contractorTitle: "Je suis Entrepreneur",
    contractorDesc: "Gérer les clients, les permis, les tâches et les calendriers de projet",
    contractorButton: "Accéder au Tableau de Bord Admin",
    homeownerTitle: "Je suis Propriétaire",
    homeownerDesc: "Voir l'état de votre projet, les documents et communiquer avec votre entrepreneur",
    homeownerButton: "Voir Mes Projets",
    myProjects: "Mes Projets",
    projectStatus: "État du Projet",
    inProgress: "En Cours",
    projectProgress: "Progression du Projet",
    excellentProgress: "Excellent progrès! Votre projet est presque terminé.",
    greatProgress: "Bon progrès! Votre projet est sur la bonne voie.",
    goodStart: "Bon début! Votre projet progresse bien.",
    justBegun: "Votre projet vient de commencer.",
    timeline: "Calendrier",
    weeks: "Semaines",
    documents: "Documents",
    photos: "Photos",
    messages: "Messages",
    new: "Nouveau",
    recentUpdates: "Mises à Jour Récentes",
    upcomingMilestones: "Jalons à Venir",
    contactContractor: "Contactez Votre Entrepreneur",
    contactDesc: "Des questions? Envoyez un message à votre équipe d'entrepreneurs.",
    sendMessage: "Envoyer un Message",
    loadingProgress: "Chargement en cours...",
    propertyValue: "Valeur de la Propriété",
    currentValue: "Valeur Actuelle de la Propriété",
    postRenovationValue: "Valeur Post-Rénovation",
    estimatedIncrease: "Augmentation Estimée de la Valeur",
    roi: "ROI",
    aiRenovationVisualizer: "Visualiseur de Rénovation IA",
    // Landing page
    heroTitle: "La Plateforme Complète pour les Projets de Construction",
    heroSubtitle: "Que vous soyez un entrepreneur gérant plusieurs clients ou un propriétaire suivant votre rénovation, Assemble connecte tout le monde et maintient les projets sur la bonne voie.",
    getStartedFree: "Commencer Gratuitement",
    watchDemo: "Voir la Démo",
    forContractors: "Pour les Entrepreneurs",
    contractorSubtitle: "Des outils puissants pour rationaliser votre entreprise de construction et gérer plusieurs projets facilement.",
    forHomeowners: "Pour les Propriétaires",
    homeownerSubtitle: "Restez connecté et informé tout au long de votre parcours de rénovation avec des mises à jour en temps réel et une communication directe.",
    clientManagement: "Gestion des Clients",
    clientManagementDesc: "Gardez une trace de tous vos clients et des détails de leurs projets dans un emplacement centralisé.",
    projectScheduling: "Planification des Projets",
    projectSchedulingDesc: "Planifiez et visualisez les délais de vos projets avec un système de calendrier intégré.",
    permitTracking: "Suivi des Permis",
    permitTrackingDesc: "Surveillez les demandes et approbations de permis pour maintenir les projets conformes et à temps.",
    taskManagement: "Gestion des Tâches",
    taskManagementDesc: "Attribuez, suivez et gérez les tâches au sein de votre équipe avec des niveaux de priorité et des dates d'échéance.",
    propertyValueTracking: "Suivi de la Valeur de la Propriété",
    propertyValueTrackingDesc: "Surveillez l'augmentation estimée de la valeur de votre propriété au fur et à mesure de l'avancement de votre rénovation.",
    realTimeUpdates: "Mises à Jour de Progression en Temps Réel",
    realTimeUpdatesDesc: "Restez informé avec des mises à jour de projet en direct et un suivi des jalons pendant votre rénovation.",
    photoDocumentation: "Documentation Photographique",
    photoDocumentationDesc: "Accédez à toutes les photos du projet et aux mises à jour visuelles de progression dans une galerie organisée.",
    directCommunication: "Communication Directe",
    directCommunicationDesc: "Envoyez des messages aux entrepreneurs directement et obtenez des réponses rapides à toutes vos questions.",
    pricing: "Tarifs Simples et Transparents",
    pricingSubtitle: "Choisissez le plan qui correspond à vos besoins. Tous les plans incluent un essai gratuit de 14 jours.",
    mostPopular: "Le Plus Populaire",
    perMonth: "/mois",
    startFreeTrial: "Commencer l'Essai Gratuit",
    readyToStart: "Prêt à Commencer?",
    readySubtitle: "Rejoignez des milliers d'entrepreneurs et de propriétaires qui gèrent leurs projets plus efficacement",
    getStartedToday: "Commencer Aujourd'hui",
    getStarted: "Commencer",
  },
  de: {
    welcomeTitle: "Willkommen bei Assemble",
    welcomeSubtitle: "Wählen Sie Ihre Rolle zum Starten",
    contractorTitle: "Ich bin Auftragnehmer",
    contractorDesc: "Verwalten Sie Kunden, Genehmigungen, Aufgaben und Projektpläne",
    contractorButton: "Zum Admin-Dashboard",
    homeownerTitle: "Ich bin Hausbesitzer",
    homeownerDesc: "Sehen Sie Ihren Projektstatus, Dokumente und kommunizieren Sie mit Ihrem Auftragnehmer",
    homeownerButton: "Meine Projekte Ansehen",
    myProjects: "Meine Projekte",
    projectStatus: "Projektstatus",
    inProgress: "In Bearbeitung",
    projectProgress: "Projektfortschritt",
    excellentProgress: "Ausgezeichneter Fortschritt! Ihr Projekt ist fast fertig.",
    greatProgress: "Guter Fortschritt! Ihr Projekt läuft planmäßig.",
    goodStart: "Guter Start! Ihr Projekt macht gute Fortschritte.",
    justBegun: "Ihr Projekt hat gerade begonnen.",
    timeline: "Zeitplan",
    weeks: "Wochen",
    documents: "Dokumente",
    photos: "Fotos",
    messages: "Nachrichten",
    new: "Neu",
    recentUpdates: "Neueste Updates",
    upcomingMilestones: "Kommende Meilensteine",
    contactContractor: "Kontaktieren Sie Ihren Auftragnehmer",
    contactDesc: "Haben Sie Fragen? Senden Sie eine Nachricht an Ihr Auftragnehmer-Team.",
    sendMessage: "Nachricht Senden",
    loadingProgress: "Lädt Fortschritt...",
    propertyValue: "Immobilienwert",
    currentValue: "Aktueller Immobilienwert",
    postRenovationValue: "Wert Nach Renovierung",
    estimatedIncrease: "Geschätzte Wertsteigerung",
    roi: "ROI",
    aiRenovationVisualizer: "KI-Renovierungs-Visualisierer",
    // Landing page
    heroTitle: "Die Komplette Plattform für Bauprojekte",
    heroSubtitle: "Egal, ob Sie ein Auftragnehmer sind, der mehrere Kunden verwaltet, oder ein Hausbesitzer, der seine Renovierung verfolgt, Assemble verbindet alle und hält Projekte auf Kurs.",
    getStartedFree: "Kostenlos Starten",
    watchDemo: "Demo Ansehen",
    forContractors: "Für Auftragnehmer",
    contractorSubtitle: "Leistungsstarke Tools zur Optimierung Ihres Auftragnehmgeschäfts und zur einfachen Verwaltung mehrerer Projekte.",
    forHomeowners: "Für Hausbesitzer",
    homeownerSubtitle: "Bleiben Sie während Ihrer Renovierungsreise mit Echtzeit-Updates und direkter Kommunikation verbunden und informiert.",
    clientManagement: "Kundenverwaltung",
    clientManagementDesc: "Behalten Sie alle Ihre Kunden und deren Projektdetails an einem zentralen Ort im Blick.",
    projectScheduling: "Projektplanung",
    projectSchedulingDesc: "Planen und visualisieren Sie Ihre Projekttermine mit einem integrierten Kalendersystem.",
    permitTracking: "Genehmigungsverfolgung",
    permitTrackingDesc: "Überwachen Sie Genehmigungsanträge und -genehmigungen, um Projekte konform und termingerecht zu halten.",
    taskManagement: "Aufgabenverwaltung",
    taskManagementDesc: "Weisen Sie Aufgaben in Ihrem Team zu, verfolgen und verwalten Sie sie mit Prioritätsstufen und Fälligkeitsdaten.",
    propertyValueTracking: "Immobilienwertverfolgung",
    propertyValueTrackingDesc: "Überwachen Sie die geschätzte Wertsteigerung Ihrer Immobilie, während Ihre Renovierung fortschreitet.",
    realTimeUpdates: "Echtzeit-Fortschrittsaktualisierungen",
    realTimeUpdatesDesc: "Bleiben Sie mit Live-Projektaktualisierungen und Meilensteinverfolgung während Ihrer Renovierung informiert.",
    photoDocumentation: "Fotodokumentation",
    photoDocumentationDesc: "Greifen Sie auf alle Projektfotos und visuellen Fortschrittsaktualisierungen in einer organisierten Galerie zu.",
    directCommunication: "Direkte Kommunikation",
    directCommunicationDesc: "Senden Sie Nachrichten direkt an Auftragnehmer und erhalten Sie schnelle Antworten auf alle Ihre Fragen.",
    pricing: "Einfache, Transparente Preise",
    pricingSubtitle: "Wählen Sie den Plan, der Ihren Anforderungen entspricht. Alle Pläne beinhalten eine 14-tägige kostenlose Testversion.",
    mostPopular: "Am Beliebtesten",
    perMonth: "/Monat",
    startFreeTrial: "Kostenlose Testversion Starten",
    readyToStart: "Bereit zu Starten?",
    readySubtitle: "Schließen Sie sich Tausenden von Auftragnehmern und Hausbesitzern an, die ihre Projekte effizienter verwalten",
    getStartedToday: "Heute Starten",
    getStarted: "Starten",
  },
  zh: {
    welcomeTitle: "欢迎来到 Assemble",
    welcomeSubtitle: "选择您的角色开始",
    contractorTitle: "我是承包商",
    contractorDesc: "管理客户、许可证、任务和项目进度",
    contractorButton: "访问管理员仪表板",
    homeownerTitle: "我是房主",
    homeownerDesc: "查看您的项目状态、文件并与承包商沟通",
    homeownerButton: "查看我的项目",
    myProjects: "我的项目",
    projectStatus: "项目状态",
    inProgress: "进行中",
    projectProgress: "项目进度",
    excellentProgress: "进展优秀！您的项目即将完成。",
    greatProgress: "进展良好！您的项目正在按计划进行。",
    goodStart: "开始不错！您的项目进展顺利。",
    justBegun: "您的项目刚刚开始。",
    timeline: "时间表",
    weeks: "周",
    documents: "文件",
    photos: "照片",
    messages: "消息",
    new: "新",
    recentUpdates: "最近更新",
    upcomingMilestones: "即将到来的里程碑",
    contactContractor: "联系您的承包商",
    contactDesc: "有问题吗？向您的承包商团队发送消息。",
    sendMessage: "发送消息",
    loadingProgress: "加载进度中...",
    propertyValue: "房产价值",
    currentValue: "当前房产价值",
    postRenovationValue: "装修后价值",
    estimatedIncrease: "预估价值增长",
    roi: "投资回报率",
    aiRenovationVisualizer: "AI 装修可视化工具",
    // Landing page
    heroTitle: "完整的建筑项目平台",
    heroSubtitle: "无论您是管理多个客户的承包商，还是跟踪装修的房主，Assemble 都能连接所有人并保持项目顺利进行。",
    getStartedFree: "免费开始",
    watchDemo: "观看演示",
    forContractors: "适用于承包商",
    contractorSubtitle: "强大的工具可简化您的承包业务并轻松管理多个项目。",
    forHomeowners: "适用于房主",
    homeownerSubtitle: "通过实时更新和直接沟通，在您的装修过程中保持联系和了解情况。",
    clientManagement: "客户管理",
    clientManagementDesc: "在一个集中位置跟踪所有客户及其项目详细信息。",
    projectScheduling: "项目安排",
    projectSchedulingDesc: "使用集成的日历系统规划和可视化项目时间表。",
    permitTracking: "许可证跟踪",
    permitTrackingDesc: "监控许可证申请和批准，以保持项目合规和按时完成。",
    taskManagement: "任务管理",
    taskManagementDesc: "在您的团队中分配、跟踪和管理具有优先级和截止日期的任务。",
    propertyValueTracking: "房产价值跟踪",
    propertyValueTrackingDesc: "随着装修的进展，监控您房产的预估价值增长。",
    realTimeUpdates: "实时进度更新",
    realTimeUpdatesDesc: "在装修期间通过实时项目更新和里程碑跟踪保持了解。",
    photoDocumentation: "照片文档",
    photoDocumentationDesc: "在有组织的画廊中访问所有项目照片和可视化进度更新。",
    directCommunication: "直接沟通",
    directCommunicationDesc: "直接向承包商发送消息，并快速获得所有问题的答案。",
    pricing: "简单透明的价格",
    pricingSubtitle: "选择适合您需求的计划。所有计划包括 14 天免费试用。",
    mostPopular: "最受欢迎",
    perMonth: "/月",
    startFreeTrial: "开始免费试用",
    readyToStart: "准备开始了吗？",
    readySubtitle: "加入数千名更高效管理项目的承包商和房主",
    getStartedToday: "今天开始",
    getStarted: "开始",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
